version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./compose/app/Dockerfile
    environment:
      - VK_APP_ID=0123456
      - VK_APP_SECRET_KEY=abcdefghijklmnopqrst
    volumes:
      - application_static:/application/static
    depends_on:
      - redis

  redis:
    image: redis:latest

  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    expose:
      - 80
    ports:
      - 80:80
      - 443:443
    volumes:
      - application_static:/application/static
    depends_on:
      - app


volumes:
  application_static: